# Generated by Django 6.1 on 2026-08-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("rack_id", models.IntegerField(blank=True, null=True)),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Mean of all observed prices for this station, USD per gallon.",
                        max_digits=8,
                    ),
                ),
                ("price_sample_count", models.PositiveSmallIntegerField(default=1)),
                ("price_min", models.DecimalField(decimal_places=5, max_digits=8)),
                ("price_max", models.DecimalField(decimal_places=5, max_digits=8)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "geocode_precision",
                    models.CharField(
                        choices=[
                            ("unknown", "Not geocoded"),
                            ("city", "City centroid"),
                            ("poi", "Matched OSM fuel POI"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["opis_id"],
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"], name="station_latlon_idx"
                    ),
                    models.Index(fields=["retail_price"], name="station_price_idx"),
                    models.Index(
                        fields=["state", "city"], name="station_state_city_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__isnull", True),
                            models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                            _connector="OR",
                        ),
                        name="station_latitude_in_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__isnull", True),
                            models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                            _connector="OR",
                        ),
                        name="station_longitude_in_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("retail_price__gt", 0)),
                        name="station_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price_min__lte", models.F("price_max"))),
                        name="station_price_spread_ordered",
                    ),
                ],
            },
        ),
    ]
